pyspatialite for in-memory db unit tests
Still not working. Not sure what is causing the error below because it
looks fine to me:

IntegrityError: (IntegrityError) occurrences.location violates Geometry
constraint [geom-type or SRID not allowed]

INSERT INTO occurrences (location, rating, species_id, source_id,
source_record_id) VALUES (?, ?, ?, ?, ?)' ('POINT (8.0000000000000000
7.0000000000000000)', 'invalid', 2, 1, <read-only buffer for 0x95f6908,
size -1, offset 0 at 0x960a4c0>)